import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = process.argv[2] === "production";

// Read xterm CSS
const xtermCssPath = path.join("node_modules", "@xterm", "xterm", "css", "xterm.css");
let xtermCss = "";
try {
    xtermCss = fs.readFileSync(xtermCssPath, "utf-8");
    // Escape backticks and backslashes for template literal
    xtermCss = xtermCss.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
} catch (e) {
    console.warn("Warning: Could not read xterm.css, terminal may not render correctly");
}

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    define: {
        "__XTERM_CSS__": JSON.stringify(xtermCss),
    },
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    platform: "node",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
