import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
];

// Deploy build artifacts to one or more Obsidian vault plugin directories.
// Configure either:
//   - env var OBSIDIAN_PLUGIN_DIRS (colon-separated paths), or
//   - local file deploy-targets.json with: { "dirs": ["/path/to/vault/.obsidian/plugins/obsidian-llm", ...] }
function getDeployDirs() {
  const fromEnv = (process.env.OBSIDIAN_PLUGIN_DIRS || "")
    .split(":")
    .map((d) => d.trim())
    .filter(Boolean);

  let fromFile = [];
  if (existsSync("deploy-targets.json")) {
    try {
      const cfg = JSON.parse(readFileSync("deploy-targets.json", "utf-8"));
      if (Array.isArray(cfg.dirs)) fromFile = cfg.dirs;
    } catch (err) {
      console.warn(`[deploy] Failed to read deploy-targets.json: ${err.message}`);
    }
  }

  return [...new Set([...fromEnv, ...fromFile])];
}

function deploy() {
  const dirs = getDeployDirs();
  if (dirs.length === 0) return;

  const files = ["main.js", "styles.css", "manifest.json"];
  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    for (const file of files) {
      try {
        copyFileSync(file, join(dir, file));
      } catch (err) {
        console.warn(`[deploy] Failed to copy ${file} -> ${dir}: ${err.message}`);
      }
    }
    console.log(`[deploy] Copied to ${dir}`);
  }
}

const plugins = prod
  ? []
  : [
      {
        name: "deploy-on-rebuild",
        setup(build) {
          build.onEnd((result) => {
            if (result.errors.length === 0) deploy();
          });
        },
      },
    ];

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins,
});

if (prod) {
  await context.rebuild();
  deploy();
  process.exit(0);
} else {
  await context.watch();
}
